### ISSUE TITLE
Implement a sort-keys function

### ISSUE THREAD

**Issue by zkry** [zkry/yaml-pro#17]
Using tree-sitter, it would be useful to have a command to sort the keys in a map.

So this would transfer the following document:
```yaml
keys:
  ddd: 9
  bbb: 2
  ccc: 8
  aaa: 1
```

into
```yaml
keys:
  aaa: 1
  bbb: 2
  ccc: 8
  ddd: 9
```

when run on the key `keys:`.
