### ISSUE TITLE
Bug: yaml-pro-ts-paste-subtree wrong-type-argument wholenump -2

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#22]
To reproduce:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 1m
```

1. copy line 1 and 2
2. yank in another buffer
3. error: wrong-type-argument wholenump -2

Backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument wholenump -2)
  yaml-pro-ts-paste-subtree()
  yaml-pro-ts-yank(nil)
  funcall-interactively(yaml-pro-ts-yank nil)
  command-execute(yaml-pro-ts-yank)
```
