### ISSUE TITLE
yaml-pro-indent-subtree at beginning of line indents element on line above

### ISSUE THREAD

**Issue by antifuchs** [zkry/yaml-pro#26]
First I thought `yaml-pro-indent-subtree` was broken, but it has a kind of twisted logic! With the following code:

```yaml
baz:
  bar:
    x: 1
    y:
  foo:
    x: 2
    y: 4
```

## point at column 0:
With point at the very beginning of the line of the `foo:` key, a `yaml-pro-indent-subtree` will result in:

```yaml
baz:
  bar:
    x: 1
      y:
  foo:
    x: 2
    y: 4
```

## point at column 1:
With point one character ahead, the tree results in:

```yaml
baz:
    bar:
      x: 1
      y:
    foo:
      x: 2
      y: 4
```

... it indents both the `bar:` and `foo:` subtree. Weird, also not what I meant to do. But at least the syntax checks out!

## point at column 2:

That's what I actually meant to do!
```yaml
baz:
  bar:
    x: 1
    y:
    foo:
      x: 2
      y: 4
```

## Special case: `foo` at column zero

This does the right thing, resulting in a buffer transform from:

```yaml
baz:
  bar:
    x: 1
    y:
foo:
  x: 2
  y: 4
```
to:
```yaml
baz:
  bar:
    x: 1
    y:
  foo:
    x: 2
    y: 4
```

but point remains at column 0, which means that if I attempt to unindent the tree again, it'll catch the wrong target & unindent the `y` key above it.
