### ISSUE TITLE
yaml-pro-ts-next-subtree supports list items

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#31]
e.g. 

```yaml
  volumes:
    - name: global-tekton-run
      hostPath:
        path: /mnt/d1/global-tekton-run

    - name: docker-registry-auth
      secret:
        secretName: docker-registry-auth

    - name: containers
      emptyDir: {}
```

* When the point is at the first `-`, `yaml-pro-ts-next-subtree` should goto the second `-`; and similar for `yaml-pro-ts-prev-subtree`.

* When the point is at the first `name`,  `yaml-pro-ts-up-level` should goto the first `-`.
