### ISSUE TITLE
Support: yaml-pro-edit-ts-scalar uses original output type

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#32]
Given this yaml content:

```yaml
    - name: dockerfile-generator-script
      default: ""
      description: |
        line 1
        line 2
```

`yaml-pro-edit-ts-scalar` changes output type to `|+`:

<img width="772" alt="image" src="https://github.com/zkry/yaml-pro/assets/10142314/9ff787ab-1100-4e17-a701-7391bca8901e">

More sensible for me to use the original tyoe `|`.
