### ISSUE TITLE
yaml-pro stops working with polymode enabled

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#46]
To reproduce:

Configure:

```emacs-lisp
(require 'polymode)

(define-innermode poly-bash-innermode
  :mode 'bash-ts-mode
  :head-matcher "^ *#!/usr/bin/env \\(sh\\|bash\\)\n"
  :tail-matcher "^ *# </bash>$"
  :head-mode 'body
  :tail-mode 'body)

(define-hostmode poly-yaml-ts-hostmode
  :mode 'yaml-ts-mode)

(define-polymode poly-yaml-ts-mode
  :hostmode 'poly-yaml-ts-hostmode
  :innermodes
  '(poly-bash-innermode))

(add-hook 'yaml-ts-mode-hook 'poly-yaml-ts-mode)
```

Open test.yaml:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bash-v1
spec:
  params:
    - name: args
      type: array
      default: []
    - name: script
  steps:
    - name: execute
      script: |
        #!/usr/bin/env bash

        set -exu -o pipefail +o histexpand
        shopt -s inherit_errexit extglob

        # </bash>
```

<img width="591" alt="image" src="https://github.com/zkry/yaml-pro/assets/10142314/81f17c8e-a77c-45e7-9e7c-c618abc2921a">

Call `yaml-pro-ts-kill-subtree` on any key, nothing happens,
other subtree jump commands don't work neither.

Have no idea the problem is from yaml-pro or polymode, some help appreciated, thanks.
