### ISSUE TITLE
yaml-pro-ts-kill-subtree not works for list item

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#48]
To reproduce:

Given test.yaml:

```yaml
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-v1
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    app.kubernetes.io/version: "1.0.11"

spec:
  workspaces:
    - name: affinity-assistant-placeholder

  params:
    - name: context-path

    - name: dockerfile-content
      default: ""
```

Point on whichever list item (`-` char), call `yaml-pro-ts-kill-subtree`, 

* Expected: list item deleted
* Actual: list's parent deleted

BTW, `yaml-pro-ts-mark-subtree` works for list items.
