### ISSUE TITLE
[feature request] Anchor and alias

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#54]
Given this yaml:

```yaml
definitions:
  steps:
    # define
    - step: &build-test
        name: Build and test
        script:
          - mvn package
        artifacts:
          - target/**
    - step: &deploy
        name: Deploy
        deployment: test
        script:
          - ./deploy.sh target/my-app.jar

pipelines:
  branches:
    develop:
      # ref
      - step: *build-test
      - step: *deploy
    main:
      - step: *build-test
      - step:
          # ref and patch
          <<: *deploy
          deployment: production
          trigger: manual

```
Wish list:

* Jump to anchor (`&`) from alias (`*`)
* Select and jump to alias from anchor
* Select and insert alias after `*`
