### ISSUE TITLE
yaml-pro-edit-ts-scalar, support changing mode in *yaml-pro-edit* buffer

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#58]
Given `test.yaml`:

```yaml
a: |
  {
    "a": "b",
    "x": 1
  }
```

Steps to reproduce:

1. `yaml-pro-edit-ts-scalar` on key `a`'s value
2. `*yaml-pro-edit*` buffer displayed in `fundamental-mode`
3. `json-ts-mode`
4. Error: `C-c C-c is undefined`
