### ISSUE TITLE
yaml-pro-edit-scalar breaks on empty lines padding, trailing external comments

### ISSUE THREAD

**Issue by aogier** [zkry/yaml-pro#68]
Hi, for readability sake I often use empty lines padding when using scalars, such as:

```yaml

foo:
  bar: |
    
    set -x

    echo helloworld
```

this unfortunately seems to break edit-scalar feature, which fails with `yaml-pro-edit-scalar: No value found at point`

This snippet fails with an `Wrong type argument: number-or-marker-p, nil` and I'm not sure where the actual difference is:

```yaml
---
variables:
  foo: bar

meh:
  image: ffoo
  only:
    - foo
    - bar
  services:
    - name: xxx
      command:
        - mehmeh
  script:
    - |

      set -x

      echo foobar
```

What I've had an hard time to figure out is, feature breaks if at least one scalar block in file has a trailing whitespage, eg. this still breaks on first scalar again w/ a `Wrong type argument: number-or-marker-p, nil` error:

```yaml
---
variables:
  foo: bar

zmeh:
  image: ffoo
  only:
    - foo
    - bar
  services:
    - name: xxx
      command:
        - mehmeh
  script:
    - |
        set -x

        echo foobar

meh:
  image: ffoo
  only:
    - foo
    - bar
  services:
    - name: xxx
      command:
        - mehmeh
  script:
    - |

        set -x

        echo foobar

```

Also, when scalar are followed by not-in-scalar comments, feature also breaks, this snippet:
```yaml
---
foo: |
  one

  two

# not-in-scalar comment
bar: baz
```
after edit become:
```yaml
---
foo: |
    one

    two

  # not-in-scalar comment
bar: baz

```

I have no idea on how to fix it but I'd really like to use this extension so thank you in advance if you can consider this report, regards and thanks for your work :)
