### ISSUE TITLE
yaml-pro-ts-yank doesn't work correctly with delete-selection-mode

### ISSUE THREAD

**Issue by Flowneee** [zkry/yaml-pro#71]
I am currently experiencing problems with how `yaml-pro` interacts with `delete-selection-mode`: in _most_ situation it acts as if `delete-selection-mode` is disabled, for example for this file 

```yaml
a: 1
b:
  b.a: 2
  b.b: 3
```

if I am copy first line and try to insert it instead of b.a (selecting this entire line and press C-y) replaced it appends inserted line at cursor:

```yaml
# expected
a: 1
b:
  a: 1
  b.b: 3

# actual
a: 1
b:
  b.a: 2a: 1
  b.b: 3
```

It only works as expected (replacing selected region) if `yaml-pro-ts-yank-subtrees` set to `nil` AND inserted text is some "complex" YAML

My `yaml-pro` configuration

```elisp
(use-package yaml-pro
  :mode ("\\.ya?ml\\'" . yaml-ts-mode)
  :hook ((yaml-ts-mode . subword-mode)
         (yaml-ts-mode . yaml-pro-ts-mode)))
```

versions

* emacs: 29.4
* yaml: 20250208.1534
* yaml-pro: 20241223.1723
