### ISSUE TITLE
Yaml-pro edit incorrect indentation in lists:

### ISSUE THREAD

**Issue by zkry** [zkry/yaml-pro#9]
Executing `yaml-pro-edit-scalar` on the following snippet at HERE
```
    spec:
      containers:
      - name: HERE
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

produces a block scalar with incorrect indentation:
    spec:
      containers:
      - name: >-
        HERE
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

The item HERE should be indented one level deeper.
